version: '3.9'
name: 'rinha-de-backend'

services:
  spring-api1:
    image: willrodrigues/rinha-spring-api:latest
    hostname: spring-api1
    environment:
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha123
    depends_on:
      db-postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.05GB'
    networks:
      - app-network

  spring-api2:
    image: willrodrigues/rinha-spring-api:latest
    hostname: spring-api2
    environment:
      - SERVER_PORT=8000
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha123
    depends_on:
      db-postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.05GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.3GB'
    networks:
      - app-network

  db-postgresql:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
    networks:
      - app-network

networks:
  app-network:
