version: '3.9'
name: 'rinha-de-backend'

services:
  db-postgresql:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    ports:
      - 54321:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
