version: '3.9'
name: 'rinha-de-backend'

services:
  spring-api1:
    image: # TODO
    hostname: spring-api1
    depends_on:
      db-postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 0.35
          memory: 725m
    networks:
      - app-network

  spring-api2:
    image: # TODO
    hostname: spring-api2
    depends_on:
      db-postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 0.35
          memory: 725m
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 300m
    networks:
      - app-network

  db-postgresql:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: 0.5
          memory: 1250m
    networks:
      - app-network

networks:
  app-network:
